### ISSUE TITLE
wheneverを使用した定期実行でGem::GemNotFoundExceptionエラーが発生する

### ISSUE THREAD

**Issue by mugihouse** [mugihouse/auto_do_application#55]
- 質問内容
wheneverを使用して定期実行し、指定した時間になったらLINEへメッセージを送信したいと思っています。
crontabを実行させるときにエラーが出てしまい、メッセージを送ることができませんでした。
このエラーを解消したいです。

- 現状発生している問題・エラーメッセージ
```
log/cron.log

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.4.10) required by your /Users/home/workspace/runteq/noritama/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.10`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'
```
- どの処理までうまく動いているのか
rake 'remind_task:remind_today_task'を実行するとLINEへメッセージが送られました。
そのためcron実行時に原因があると考えています。

- 該当のソースコード
```
Gemfile追加分
# cron
gem 'whenever', require: false

```
```
Gemfile.lock追加分
GEM
  specs:
    chronic (0.10.2)

    whenever (1.0.0)
      chronic (>= 0.6.3)

DEPENDENCIES
  whenever
```

```
lib/tasks/remind_task.rake

namespace :remind_task do
  desc 'タスクを夕ご飯の1時間後に配信'
  task remind_today_task: :environment do
    time = Time.now.strftime("%H:%M")
    users = User.all

    # Userの夕ご飯+1時間==timeの時配信
    client = Line::Bot::Client.new do |config|
      config.channel_secret = ENV['BOT_CHANNEL_SECRET']
      config.channel_token = ENV['BOT_CHANNEL_TOKEN']
    end

    users.each do |user|
      if user.profile.dinner_time.strftime("%H:%M") == time
        line_id = user.line_id
        message = { type: 'text', text: '今日のタスク'}
        client.push_message(line_id, message)
      end
    end
  end
end
```
```
config/schedule.rb
# Rails.rootを使用
require File.expand_path(File.dirname(__FILE__) + "/environment")

# cronを実行する環境変数
rails_env = ENV['RAILS_ENV'] || :development

# cronを実行する環境変数をセット
set :environment, rails_env

# cronのログの吐き出し場所
set :output, "#{Rails.root}/log/cron.log"

#定期実行したい処理を記入
every 1.minutes do
  rake 'remind_task:remind_today_task'
end
```
```
home@shimizuyuuri noritama % bundle -v
Bundler version 2.4.10
home@shimizuyuuri noritama % ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
home@shimizuyuuri noritama % which bundler
/Users/home/.rbenv/shims/bundler
```
- エラーから考えられる原因
bundlerのバージョンはGemfileと一致していました。
エラーメッセージよりrubyのバージョン2.6.0を使おうとしていることでバージョンが合っていないとエラーが出ていると考えています。
ただ、どこでrubyのバージョンを設定できるのかがわからず止まっている状態です。

- 試したこと
  - bundlerのバージョンがGemfileと一致しているか確認
  - bundle update --bundlerを試しましたが、version2.4.19に上がってしまったため、アンインストールしました。
https://qiita.com/Miyayan/items/f5eeac0f75c33ad56295

**Comment by kenchasonakai** [comment]
本番環境で何を使ってデプロイをするのかによってcronの実行方法が変わってくると思うので前提を共有していただきたいです

たとえばHerokuの場合はHerokuのschedulerというものを使うのでそもそもwheneverの設定が不要かと思います
https://qiita.com/sharesence/items/74a85a08add91a0fd8d8
